# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170413_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='news.Category'),
        ),
    ]
